### ISSUE TITLE
Понять почему при обновлении nestjs-pino с версии 1.4.0 до версии 2.2.0 пропадает traceId из логов

### ISSUE THREAD

**Issue by KillWolfVlad** [Byndyusoft/nest-template#32]
Вроде бы middleware начинают выполняться в другом порядке, но почему?

**Comment by KillWolfVlad** [comment]
Также стоит проверить измененный error handler - https://github.com/iamolegga/nestjs-pino/issues/535#issuecomment-973864551

**Comment by iamolegga** [comment]
Увидел референс в issue, решил отписаться, чтоб вы не тратили время: просто обновитесь до последней версии, там проблема [решена](https://github.com/iamolegga/nestjs-pino/pull/663/files)

**Comment by KillWolfVlad** [comment]
@iamolegga спасибо за совет. Новая версия nestjs-pino нормально работает со стандартным ExceptionFilter. https://github.com/iamolegga/nestjs-pino/issues/535 логирование двух ошибок сохраняется. Также у нас была проблема, что из-за того что LoggerCoreModule убрали `distance` у middleware уменьшился и она всегда регистрировалась первее нашей middleware для трассировки. Пришлось обернуть LoggerModule в еще один модуль, чтобы увеличить `distance`. Во всем виновата топологическая сортировка в NestJS.

**Comment by iamolegga** [comment]
Да, есть такая проблема у фреймворка, если возникнет у самописных модулей можете попробовать в дальнейшем https://github.com/iamolegga/nestjs-configure-after

**Comment by KillWolfVlad** [comment]
Спасибо, будем знать)))
