### ISSUE TITLE
[RnD] Find jest-sonar-reporter alternatives, because it was updated 4 years ago and archived on GitHub

### ISSUE THREAD

**Issue by KillWolfVlad** [Byndyusoft/nest-template#82]
- [ ] Why repo archived?
- [ ] Report tests into Sonar

**Comment by ryabukhinstep** [comment]
Из актуальных нашел только форк [пакета](https://github.com/3dmind/jest-sonar-reporter), которым сейчас пользуемся - https://github.com/CasualBot/jest-sonar-reporter.
Форк переведен на TS. Последнее обновление полгода назад.
Проверено локально на актуальной на текущий момент версии SonarQube Version 9.6.1

Так же можем рассмотреть разработку своего репортера для Test Execution Report. Формат не сложный:
Формат: https://docs.sonarqube.org/latest/analysis/generic-test/
Jest custom report: https://jestjs.io/docs/configuration#custom-reporters

**Comment by litichevskiydv** [comment]
В следующую среду 05.10 решим, что делаем

**Comment by KillWolfVlad** [comment]
We would use this fork: https://github.com/Byndyusoft/nest-template/issues/91
